# Generated by Django 5.1.1 on 2024-12-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_follower_post_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
