# Generated by Django 5.1.1 on 2024-12-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_alter_post_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="like_count",
        ),
    ]
